# Generated by Django 4.2.6 on 2023-11-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='Bio',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='me',
            name='Phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
