# Generated by Django 4.2.6 on 2023-11-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_remove_service_status_service_descript'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
